### ISSUE TITLE
Support for multiple XTRXs

### ISSUE THREAD

**Issue by maleadt** [JuliaComputing/xtrx_julia#43]
Meta-issue to track what we need to support the XYNC:

- [x] LitePCIe kernel driver: in theory should be OK; will probe again and create new `/dev/litepcie` nodes
- [x] LiteUART driver: creates different dev nodes after https://github.com/enjoy-digital/litepcie/commit/fbab7fa339a01975cf4467c5fcc25c532ddf99fa
- [x] SoapySDR driver: support for discovering and instantiating multiple devices (https://github.com/JuliaComputing/xtrx_julia/pull/40)
  - [x] optional: selection based on device serial number, instead of unstable dev node path (https://github.com/enjoy-digital/litex/issues/1411)
  - [x] optional: ensure whether the litepcie device is an XTRX (https://github.com/JuliaComputing/xtrx_julia/pull/40)

**Comment by enjoy-digital** [comment]
@maleadt: As discussed, LiteUART driver issue should be fixed with https://github.com/enjoy-digital/litepcie/commit/fbab7fa339a01975cf4467c5fcc25c532ddf99fa (tested with 2 SQRL Acorn boards).
