### ISSUE TITLE
Control more XTRX/LMS7002M hardware from Julia

### ISSUE THREAD

**Issue by staticfloat** [JuliaComputing/xtrx_julia#74]
I started the beginning of a Julia interface to control some of the RxTSP functions from Julia in https://github.com/JuliaComputing/xtrx_julia/commit/f1227e9f2b613565fc4c29d9d0c936537404b71a.  We should increase the surface area of this API to encompass a wider range of functions.  In particular, the following pieces of functionality would be very useful:

- [ ] Enabling RxTSP/TxTSP signal blocks by toggling bypass registers (as the linked PR does):
<img width="204" alt="image" src="https://user-images.githubusercontent.com/130920/189186136-4ab89fba-2e0c-4b98-bd55-5e4ce07a29f7.png">

- [ ] Enable RxTSP/TxTSP test signal generators (TSG):
<img width="252" alt="image" src="https://user-images.githubusercontent.com/130920/189186215-0a0ac9ce-0d13-4a42-94a1-6acc390670ad.png">

- [ ] RFE analog calibration parameters for I/Q imbalance, DC offset, etc...
<img width="809" alt="image" src="https://user-images.githubusercontent.com/130920/189186597-cbbabc12-3452-4cef-ab98-8e7da3001c70.png">

Having nicely-structured APIs for getting/setting the registers for these pieces of hardware would make it a lot easier to write self-calibration code for things like #55.  In particular, it would be nice to build a way to easily get a bunch of registers, unpack them into Julian objects, then commit them back to the device.  If we want to be good neighbors, we could build this on top of SoapySDR's `writeRegister()` function, but because that uses an `std::string` it may be a little difficult to `ccall()`, so I'm also okay with us just bypassing SoapySDR and directly ccalling `libSoapyXTRX.so` with nice C types.

I envision an `XTRX.jl` package that sits on top of `SoapySDR.jl` and provides many of the more advanced, XTRX-specific pieces of functionality that we might need, such as setting advanced debugging features like the TSG, loopbacks, etc...

**Comment by sjkelly** [comment]
FWIW We now have the following in SoapySDR for more terse Settings and Registers:

```
dev = Device(Devices()[1])
dev[SoapySDR.Setting("GPS_ENABLE")] = "FALSE"
dev[(Register("LitePCI"), 0x0000)]
```

**Comment by sjkelly** [comment]
I think some of the niceties here are unaddressed, but the mechanisms are built into the driver and SoapyAPI layer. We can enable and abstract things as we need them.
