### ISSUE TITLE
Create minimal C receiver tool

### ISSUE THREAD

**Issue by staticfloat** [JuliaComputing/xtrx_julia#78]
To prove what is or is not a problem in our Julia reception stack, we should create a minimal C reproducer to stream samples off of the XTRX using the SoapySDR API and onto disk.  It should support, at a minimum, the following features:

- Specification of which SoapySDR device to load
- Specification of samplerate, frequency, gains, etc...
- The ability to stream multiple channels to multiple files (e.g. `-o file -c 2` should write out `file_1.iq` and `file_2.iq`, for the two RX channels)
- Instrumentation to measure things like how long it takes to acquire a buffer, how many DMA buffers are ready, etc...

I don't think we need to support multiple devices at this time.  [`rx_sdr` can be used as a starting point](https://github.com/rxseger/rx_tools/blob/master/src/rtl_sdr.c).

**Comment by mbaz** [comment]
Suggestions for the UI:
* Allow user to specify how many samples to record
* Allow user to specify a delay between start of sample capturing and start of actual recording

Both of these are super useful when debugging.

**Comment by sjkelly** [comment]
https://github.com/JuliaComputing/xtrx_julia/pull/98
