### ISSUE TITLE
Firmware <-> User Space Communication

### ISSUE THREAD

**Issue by sjkelly** [JuliaComputing/xtrx_julia#91]
In order to increase the sample rate, we suspect that a combination of DAC tuning for the VCTCXO and PMIC voltages will need to be adjusted. Currently the firmware controls the I2C bus. Getting data out of the firmware into a user-space readable CSR is fine as shown in https://github.com/JuliaComputing/xtrx_julia/pull/84.

However, it is not clear to me the ideal way to write a value from user space (over PCIe) into the firmware.

**Comment by enjoy-digital** [comment]
@sjkelly: The firmware is only configuring the I2C peripherals at startup. For user space control, the I2C could also be directly bit-banged from user space and we could just add a lock mechanism to avoid firmware/user space conflicts.
